name: Ruby

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the markdown blog related files
        uses: actions/checkout@v2
        with:
          repository: bsvin33t/bsvin33t
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Restore the time at which the blogposts were created
        run: git ls-files | xargs -I{} git log -1 --date=format:%Y%m%d%H%M.%S --format='touch -t %ad "{}"' "{}" | $SHELL; ls -la
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          cd blog; bundle config path vendor/bundle;
          bundle install --jobs 4 --retry 3
      - name: Build blog posts
        run: cd blog; bundle exec rake
      - name: Create static files
        run: cd blog; bundle exec jekyll build
      - name: Push the static files to the blogging repository
        run: |
          cd blog/_site; git init; \
          git config --global user.name "Vineeth";\
          git config --global user.email "bsvin33t@gmail.com";\
          git remote add origin \
          https://${{secrets.USERNAME}}:${{secrets.TOKEN}}@github.com/bsvin33t/bsvin33t.github.com.git; \
          git add .; git commit -m $(date +%Y%m%d); \
          git push origin master -f
